export type SmeMcpToolCategory =
    | 'workspace'
    | 'authoring'
    | 'operations'
    | 'advanced'
    | 'insights'

export type SmeMcpInputKind =
    | 'enum'
    | 'free_text'
    | 'number'
    | 'boolean'
    | 'reference'
    | 'object'
    | 'string_array'
    | 'object_array'

export type SmeMcpRequiredMode = 'mandatory' | 'optional' | 'conditional'

export type SmeMcpReferenceEntity =
    | 'domain'
    | 'series'
    | 'event'
    | 'course'
    | 'exam'
    | 'lesson'
    | 'asset'
    | 'template'
    | 'user'

export type SmeMcpParameterOption = {
    value: string
    label: string
    meaning?: string
}

export type SmeMcpReferenceRule = {
    entity: SmeMcpReferenceEntity
    acceptedForms: Array<'id' | 'slug' | 'name' | 'title' | 'email' | 'current_user'>
    recommendedSourceTool?: string
    matchPriority?: string[]
}

export type SmeMcpToolParameterMetadata = {
    name: string
    label: string
    inputKind: SmeMcpInputKind
    required: SmeMcpRequiredMode
    type: string
    description: string
    howToFill: string
    acceptedValues?: SmeMcpParameterOption[]
    referenceRule?: SmeMcpReferenceRule
    example?: unknown
    placeholder?: string
    defaultBehavior?: string
    aiHint?: string
    validation?: {
        minLength?: number
        maxLength?: number
        minItems?: number
        maxItems?: number
        minimum?: number
        maximum?: number
        unique?: boolean
    }
    commonMistakes?: string[]
}

export type SmeMcpToolExample = {
    title: string
    description?: string
    input: Record<string, unknown>
}

export type SmeMcpToolMetadata = {
    key: string
    label: string
    description: string
    category: SmeMcpToolCategory
    categoryLabel: string
    productionVisible?: boolean
    whenToUse: string
    inputSummary: string
    notes?: string[]
    parameters: SmeMcpToolParameterMetadata[]
    minimalExample: SmeMcpToolExample
    fullExample?: SmeMcpToolExample
    commonMistakes?: string[]
    recommendedNextActions?: string[]
}

const enumOption = (value: string, label: string, meaning?: string): SmeMcpParameterOption => ({
    value,
    label,
    meaning,
})

export const smeMcpToolMetadata: SmeMcpToolMetadata[] = [
    {
        key: 'list_my_workspace',
        label: 'List My Workspace',
        description: 'Get scoped domains, series, events, courses, exams, and gap signals.',
        category: 'workspace',
        categoryLabel: 'Workspace',
        productionVisible: true,
        whenToUse: 'Use first to discover which IDs, owners, and series are available in the current SME scope.',
        inputSummary: 'No required fields. Leave the JSON empty to inspect the whole SME scope, or add a domain filter to narrow the response.',
        notes: [
            'This is the safest first step before any create, link, or publish action.',
            'Use the returned IDs as the source of truth for later calls.',
        ],
        parameters: [
            {
                name: 'domainId',
                label: 'Domain',
                inputKind: 'reference',
                required: 'optional',
                type: 'uuid',
                description: 'Optional domain filter.',
                howToFill: 'Use a domain UUID from the current workspace when you want to narrow the response to one domain.',
                referenceRule: {
                    entity: 'domain',
                    acceptedForms: ['id'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id'],
                },
                example: '11111111-1111-1111-1111-111111111111',
                placeholder: 'Paste one domain UUID from the current scope',
                defaultBehavior: 'If omitted, the tool returns all domains, series, events, courses, exams, and gap signals in SME scope.',
                aiHint: 'Call this tool first, then reuse one of the returned IDs instead of guessing.',
            },
        ],
        minimalExample: {
            title: 'All Workspace Data',
            input: {},
        },
        fullExample: {
            title: 'One Domain Only',
            input: {
                domainId: '11111111-1111-1111-1111-111111111111',
            },
        },
        recommendedNextActions: ['create_badge', 'create_series', 'create_event', 'create_course', 'create_exam'],
    },
    {
        key: 'create_badge',
        label: 'Create Badge',
        description: 'Create a new domain badge milestone with an auto-generated slug.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use when you want to add a new badge milestone under an existing product domain.',
        inputSummary: 'Required: name, domain, thresholdStars. Slug is generated automatically from the badge name.',
        notes: [
            'Use a short milestone name such as "RTC Ready" or "RTC Practitioner".',
            'Threshold stars should increase as the ladder progresses.',
        ],
        parameters: [
            {
                name: 'name',
                label: 'Badge Name',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Learner-facing badge milestone name.',
                howToFill: 'Use a short name, usually 2-5 words.',
                example: 'RTC Ready',
                validation: { minLength: 1, maxLength: 120 },
            },
            {
                name: 'domain',
                label: 'Domain',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | slug | name',
                description: 'The product domain that owns this badge.',
                howToFill: 'Use a domain id, slug, or exact name from the workspace.',
                referenceRule: {
                    entity: 'domain',
                    acceptedForms: ['id', 'slug', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'slug', 'name'],
                },
                example: 'RTC',
            },
            {
                name: 'thresholdStars',
                label: 'Threshold Stars',
                inputKind: 'number',
                required: 'mandatory',
                type: 'integer',
                description: 'How many stars are required to unlock the badge.',
                howToFill: 'Use a positive integer that fits the badge ladder progression.',
                example: 4,
                validation: { minimum: 1, maximum: 1000 },
            },
            {
                name: 'icon',
                label: 'Icon',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Optional icon token for the badge.',
                howToFill: 'Use a short system token if you already have one; otherwise omit it.',
                example: 'READY',
                defaultBehavior: 'If omitted, the badge is created without an icon token.',
            },
            {
                name: 'description',
                label: 'Description',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Short explanation of what the badge represents.',
                howToFill: 'Use one concise sentence.',
                example: 'Earned through steady participation in RTC weekly case studies.',
            },
            {
                name: 'active',
                label: 'Active',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether the badge is enabled immediately.',
                howToFill: 'Usually keep this true.',
                example: true,
                defaultBehavior: 'Defaults to true.',
            },
        ],
        minimalExample: {
            title: 'Minimal Badge',
            input: {
                name: 'RTC Ready',
                domain: 'RTC',
                thresholdStars: 4,
            },
        },
        fullExample: {
            title: 'Full Badge',
            input: {
                name: 'RTC Ready',
                domain: 'RTC',
                thresholdStars: 4,
                icon: 'READY',
                description: 'Earned through steady participation in RTC weekly case studies.',
                active: true,
            },
        },
        recommendedNextActions: ['list_my_workspace', 'create_series'],
    },
    {
        key: 'create_series',
        label: 'Create Series',
        description: 'Create a new learning series with an auto-generated slug.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use when you want a reusable program container before creating events.',
        inputSummary: 'Required: name, seriesType, productDomain. Owner defaults to the current SME unless an admin overrides it.',
        parameters: [
            {
                name: 'name',
                label: 'Series Name',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Learner-facing series name.',
                howToFill: 'Use the recurring program name.',
                example: 'RTC Weekly Case Study',
                validation: { minLength: 1, maxLength: 160 },
            },
            {
                name: 'seriesType',
                label: 'Series Type',
                inputKind: 'enum',
                required: 'mandatory',
                type: 'enum',
                description: 'Primary type of the learning series.',
                howToFill: 'Choose the closest series type used by the training-ops model.',
                acceptedValues: [
                    enumOption('WEEKLY_DRILL', 'Weekly Drill'),
                    enumOption('CASE_STUDY', 'Case Study'),
                    enumOption('KNOWLEDGE_SHARING', 'Knowledge Sharing'),
                    enumOption('FAQ_SHARE', 'FAQ Share'),
                    enumOption('RELEASE_READINESS', 'Release Readiness'),
                    enumOption('QUARTERLY_FINAL', 'Quarterly Final'),
                    enumOption('YEAR_END_FINAL', 'Year-end Final'),
                ],
                example: 'CASE_STUDY',
            },
            {
                name: 'productDomain',
                label: 'Product Domain',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | slug | name',
                description: 'Product domain that owns this series.',
                howToFill: 'Use a domain id, slug, or exact name from the workspace.',
                referenceRule: {
                    entity: 'domain',
                    acceptedForms: ['id', 'slug', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'slug', 'name'],
                },
                example: 'RTC',
            },
            {
                name: 'seriesOwner',
                label: 'Series Owner',
                inputKind: 'reference',
                required: 'optional',
                type: 'current_user | user id | email',
                description: 'Owner of the series.',
                howToFill: 'Use current_user, a user id, or an email. SMEs default to themselves.',
                referenceRule: {
                    entity: 'user',
                    acceptedForms: ['id', 'email', 'current_user'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'current_user',
                defaultBehavior: 'Defaults to current_user.',
            },
            {
                name: 'cadence',
                label: 'Cadence',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Narrative cadence label shown in the series record.',
                howToFill: 'Use labels such as Weekly, Bi-Weekly, or Monthly.',
                example: 'Weekly',
            },
            {
                name: 'description',
                label: 'Description',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Short description of the series.',
                howToFill: 'Use 1-2 concise sentences.',
                example: 'Weekly RTC case-study program focused on troubleshooting readiness.',
            },
            {
                name: 'active',
                label: 'Active',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether the series is active immediately.',
                howToFill: 'Usually keep this true.',
                example: true,
                defaultBehavior: 'Defaults to true.',
            },
            {
                name: 'contributesToDomainBadges',
                label: 'Contributes To Domain Badges',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether the series should be badge-eligible.',
                howToFill: 'Use true when series activity should count toward domain badge ladders.',
                example: true,
                defaultBehavior: 'Defaults to true.',
            },
        ],
        minimalExample: {
            title: 'Minimal Series',
            input: {
                name: 'RTC Weekly Case Study',
                seriesType: 'CASE_STUDY',
                productDomain: 'RTC',
            },
        },
        fullExample: {
            title: 'Full Series',
            input: {
                name: 'RTC Weekly Case Study',
                seriesType: 'CASE_STUDY',
                productDomain: 'RTC',
                seriesOwner: 'current_user',
                cadence: 'Weekly',
                description: 'Weekly RTC case-study program focused on troubleshooting readiness.',
                active: true,
                contributesToDomainBadges: true,
            },
        },
        recommendedNextActions: ['create_event', 'list_my_workspace'],
    },
    {
        key: 'create_event',
        label: 'Create Event',
        description: 'Create a new learning event under an existing learning series.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use when you want to schedule or draft an event before attaching a course or exam.',
        inputSummary: 'Required: title, learningSeries, format. Status defaults to DRAFT and host defaults to current_user.',
        parameters: [
            {
                name: 'title',
                label: 'Event Title',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Learner-facing event title.',
                howToFill: 'Use the actual session topic or event title.',
                example: 'RTC Case Study - Video Quality',
                validation: { minLength: 1, maxLength: 200 },
            },
            {
                name: 'learningSeries',
                label: 'Learning Series',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | slug | name',
                description: 'Series that owns this event.',
                howToFill: 'Use a series id, slug, or exact name from the workspace.',
                referenceRule: {
                    entity: 'series',
                    acceptedForms: ['id', 'slug', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'slug', 'name'],
                },
                example: 'RTC Weekly Case Study',
            },
            {
                name: 'format',
                label: 'Format',
                inputKind: 'enum',
                required: 'mandatory',
                type: 'enum',
                description: 'Learning event format.',
                howToFill: 'Choose a format allowed for the selected series type.',
                acceptedValues: [
                    enumOption('CASE_STUDY', 'Case Study'),
                    enumOption('KNOWLEDGE_SHARING', 'Knowledge Sharing'),
                    enumOption('FAQ_SHARE', 'FAQ Share'),
                    enumOption('RELEASE_BRIEFING', 'Release Briefing'),
                    enumOption('QUIZ_REVIEW', 'Quiz Review'),
                    enumOption('FINAL_EXAM', 'Final Exam'),
                    enumOption('WORKSHOP', 'Workshop'),
                ],
                example: 'CASE_STUDY',
            },
            {
                name: 'status',
                label: 'Status',
                inputKind: 'enum',
                required: 'optional',
                type: 'enum',
                description: 'Initial event status.',
                howToFill: 'Usually leave this as DRAFT unless the event is already scheduled.',
                acceptedValues: [
                    enumOption('DRAFT', 'Draft'),
                    enumOption('SCHEDULED', 'Scheduled'),
                ],
                example: 'DRAFT',
                defaultBehavior: 'Defaults to DRAFT.',
            },
            {
                name: 'host',
                label: 'Host',
                inputKind: 'reference',
                required: 'optional',
                type: 'current_user | user id | email',
                description: 'Active host for the event.',
                howToFill: 'Use current_user, a user id, or an email.',
                referenceRule: {
                    entity: 'user',
                    acceptedForms: ['id', 'email', 'current_user'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'current_user',
                defaultBehavior: 'Defaults to current_user.',
            },
            {
                name: 'productDomain',
                label: 'Product Domain',
                inputKind: 'reference',
                required: 'optional',
                type: 'id | slug | name',
                description: 'Optional explicit domain override or cross-check.',
                howToFill: 'Usually omit this because the series already determines the domain.',
                referenceRule: {
                    entity: 'domain',
                    acceptedForms: ['id', 'slug', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'RTC',
                defaultBehavior: 'If omitted, the domain is resolved from the series.',
            },
            {
                name: 'description',
                label: 'Description',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Short event description.',
                howToFill: 'Use 1-3 concise sentences.',
                example: 'Weekly review of RTC video quality issues and troubleshooting paths.',
            },
            {
                name: 'scheduledAt',
                label: 'Scheduled At',
                inputKind: 'free_text',
                required: 'optional',
                type: 'ISO 8601 datetime | null',
                description: 'Scheduled time for the event.',
                howToFill: 'Use an ISO 8601 datetime string when the event time is known.',
                example: '2026-04-28T09:00:00.000Z',
            },
            {
                name: 'countsTowardPerformance',
                label: 'Counts Toward Performance',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether this event contributes to performance tracking.',
                howToFill: 'Usually keep false for practice-style events.',
                example: false,
                defaultBehavior: 'Defaults to false.',
            },
            {
                name: 'starValue',
                label: 'Star Value',
                inputKind: 'number',
                required: 'optional',
                type: 'integer | null',
                description: 'Recognition star value for event completion.',
                howToFill: 'Use a small non-negative integer such as 1 or 2.',
                example: 2,
                validation: { minimum: 0, maximum: 20 },
            },
        ],
        minimalExample: {
            title: 'Minimal Event',
            input: {
                title: 'RTC Case Study - Video Quality',
                learningSeries: 'RTC Weekly Case Study',
                format: 'CASE_STUDY',
            },
        },
        fullExample: {
            title: 'Full Event',
            input: {
                title: 'RTC Case Study - Video Quality',
                learningSeries: 'RTC Weekly Case Study',
                format: 'CASE_STUDY',
                status: 'DRAFT',
                host: 'current_user',
                description: 'Weekly review of RTC video quality issues and troubleshooting paths.',
                scheduledAt: '2026-04-28T09:00:00.000Z',
                countsTowardPerformance: false,
                starValue: 2,
            },
        },
        recommendedNextActions: ['create_course', 'create_exam', 'review_event_status'],
    },
    {
        key: 'create_course',
        label: 'Create Course',
        description: 'Create a course and optionally bind it to an event.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use when you want to create the course shell before designing chapters, lessons, and assets.',
        inputSummary: 'Required: title. Event is optional. AI assistant defaults are applied automatically by admin policy.',
        notes: [
            'If an event is provided, the course is linked during creation.',
            'If no admin default AI template is active, the course still uses default assistant behavior and returns a warning.',
        ],
        parameters: [
            {
                name: 'title',
                label: 'Course Title',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Learner-facing course title.',
                howToFill: 'Use the final course name.',
                example: 'RTC Audio Basics Course',
            },
            {
                name: 'event',
                label: 'Event',
                inputKind: 'reference',
                required: 'optional',
                type: 'id | title',
                description: 'Optional event to bind the course to.',
                howToFill: 'Use an event id or exact title.',
                referenceRule: {
                    entity: 'event',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'RTC Audio Basics',
                defaultBehavior: 'If omitted, the course is created as standalone.',
            },
            {
                name: 'description',
                label: 'Description',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Course description.',
                howToFill: 'Use 1-3 concise sentences.',
                example: 'Introductory RTC audio troubleshooting course.',
            },
            {
                name: 'whatYouWillLearn',
                label: 'What You Will Learn',
                inputKind: 'string_array',
                required: 'optional',
                type: 'string[]',
                description: 'Learning outcomes shown to learners.',
                howToFill: 'Use 3-5 short bullet-style statements.',
                example: ['Understand RTC audio flow', 'Identify common no-audio issues'],
            },
            {
                name: 'requirements',
                label: 'Requirements',
                inputKind: 'string_array',
                required: 'optional',
                type: 'string[]',
                description: 'Prerequisites for the course.',
                howToFill: 'Use short prerequisite statements.',
                example: ['Basic RTC product knowledge'],
            },
            {
                name: 'thumbnailUrl',
                label: 'Thumbnail URL',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Optional course thumbnail URL.',
                howToFill: 'Use a full image URL.',
                example: 'https://example.com/rtc-audio-course.png',
                defaultBehavior: 'If omitted, the system default thumbnail remains in use.',
            },
            {
                name: 'category',
                label: 'Category',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Course category label.',
                howToFill: 'Use the product/domain category, such as RTC.',
                example: 'RTC',
                defaultBehavior: 'If omitted, the backend derives a category from the linked event domain or falls back to General.',
            },
            {
                name: 'level',
                label: 'Level',
                inputKind: 'enum',
                required: 'optional',
                type: 'enum',
                description: 'Course difficulty level.',
                howToFill: 'Choose the learner level.',
                acceptedValues: [
                    enumOption('BEGINNER', 'Beginner'),
                    enumOption('INTERMEDIATE', 'Intermediate'),
                    enumOption('ADVANCED', 'Advanced'),
                ],
                example: 'BEGINNER',
                defaultBehavior: 'Defaults to BEGINNER.',
            },
            {
                name: 'status',
                label: 'Status',
                inputKind: 'enum',
                required: 'optional',
                type: 'enum',
                description: 'Initial course status.',
                howToFill: 'Usually keep the course as DRAFT.',
                acceptedValues: [
                    enumOption('DRAFT', 'Draft'),
                    enumOption('PUBLISHED', 'Published'),
                    enumOption('ARCHIVED', 'Archived'),
                ],
                example: 'DRAFT',
                defaultBehavior: 'Defaults to DRAFT.',
            },
            {
                name: 'instructor',
                label: 'Instructor',
                inputKind: 'reference',
                required: 'optional',
                type: 'current_user | user id | email',
                description: 'Course instructor or owner.',
                howToFill: 'Use current_user, a user id, or an email. SMEs default to themselves.',
                referenceRule: {
                    entity: 'user',
                    acceptedForms: ['id', 'email', 'current_user'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'current_user',
                defaultBehavior: 'Defaults to current_user.',
            },
            {
                name: 'tags',
                label: 'Tags',
                inputKind: 'string_array',
                required: 'optional',
                type: 'string[]',
                description: 'Optional search and grouping tags.',
                howToFill: 'Use 2-6 short keywords.',
                example: ['rtc', 'audio', 'troubleshooting'],
            },
        ],
        minimalExample: {
            title: 'Minimal Course',
            input: {
                title: 'RTC Audio Basics Course',
                event: 'RTC Audio Basics',
            },
        },
        fullExample: {
            title: 'Full Course',
            input: {
                title: 'RTC Audio Basics Course',
                event: 'RTC Audio Basics',
                description: 'Introductory RTC audio troubleshooting course.',
                whatYouWillLearn: ['Understand RTC audio flow', 'Identify common no-audio issues'],
                requirements: ['Basic RTC product knowledge'],
                category: 'RTC',
                level: 'BEGINNER',
                instructor: 'current_user',
                tags: ['rtc', 'audio', 'troubleshooting'],
            },
        },
        recommendedNextActions: ['review_event_status'],
    },
    {
        key: 'create_exam',
        label: 'Create Exam',
        description: 'Create an exam and optionally bind it to an event.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use when you want an exam shell before adding or generating questions.',
        inputSummary: 'Required: title, examType, totalScore, passingScore, maxAttempts. Event is optional and default exam options are applied if options are omitted.',
        parameters: [
            {
                name: 'title',
                label: 'Exam Title',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Learner-facing exam title.',
                howToFill: 'Use the final exam name.',
                example: 'RTC Audio Basics Assessment',
            },
            {
                name: 'event',
                label: 'Event',
                inputKind: 'reference',
                required: 'optional',
                type: 'id | title',
                description: 'Optional event to bind the exam to.',
                howToFill: 'Use an event id or exact title.',
                referenceRule: {
                    entity: 'event',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'RTC Audio Basics',
                defaultBehavior: 'If omitted, the exam is created as standalone.',
            },
            {
                name: 'description',
                label: 'Description',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Short exam description.',
                howToFill: 'Use one concise sentence.',
                example: 'Assessment for RTC audio basics.',
            },
            {
                name: 'instructions',
                label: 'Instructions',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Instructions shown to learners.',
                howToFill: 'Explain how learners should complete the exam.',
                example: 'Read each question carefully before answering.',
            },
            {
                name: 'examType',
                label: 'Exam Type',
                inputKind: 'enum',
                required: 'mandatory',
                type: 'enum',
                description: 'Assessment intent for the exam.',
                howToFill: 'Choose the closest assessment kind.',
                acceptedValues: [
                    enumOption('PRACTICE', 'Practice', 'Training or rehearsal exam'),
                    enumOption('READINESS', 'Readiness', 'Readiness or qualification check'),
                    enumOption('FORMAL', 'Formal', 'Formal graded assessment'),
                ],
                example: 'PRACTICE',
            },
            {
                name: 'totalScore',
                label: 'Total Score',
                inputKind: 'number',
                required: 'mandatory',
                type: 'integer',
                description: 'Total score for the exam.',
                howToFill: 'Use a positive integer such as 100.',
                example: 100,
            },
            {
                name: 'passingScore',
                label: 'Passing Score',
                inputKind: 'number',
                required: 'mandatory',
                type: 'integer',
                description: 'Minimum passing score.',
                howToFill: 'Use a value less than or equal to totalScore.',
                example: 80,
            },
            {
                name: 'maxAttempts',
                label: 'Max Attempts',
                inputKind: 'number',
                required: 'mandatory',
                type: 'integer',
                description: 'Maximum number of learner attempts.',
                howToFill: 'Use a positive integer.',
                example: 3,
            },
            {
                name: 'options',
                label: 'Exam Options',
                inputKind: 'object',
                required: 'optional',
                type: 'object | null',
                description: 'Optional exam option overrides.',
                howToFill: 'Usually omit this block and let the system defaults apply. If needed, include timeLimit, randomizeQuestions, randomizeOptions, showResultsImmediately, or allowReview.',
                example: {
                    timeLimit: 30,
                    randomizeQuestions: false,
                    randomizeOptions: false,
                    showResultsImmediately: true,
                    allowReview: true,
                },
                defaultBehavior: 'If omitted, the system uses the default exam option set.',
            },
        ],
        minimalExample: {
            title: 'Minimal Exam',
            input: {
                title: 'RTC Audio Basics Assessment',
                event: 'RTC Audio Basics',
                examType: 'PRACTICE',
                totalScore: 100,
                passingScore: 80,
                maxAttempts: 3,
            },
        },
        fullExample: {
            title: 'Full Exam',
            input: {
                title: 'RTC Audio Basics Assessment',
                event: 'RTC Audio Basics',
                description: 'Assessment for RTC audio basics.',
                instructions: 'Read each question carefully before answering.',
                examType: 'PRACTICE',
                totalScore: 100,
                passingScore: 80,
                maxAttempts: 3,
                options: {
                    timeLimit: 30,
                    randomizeQuestions: false,
                    randomizeOptions: false,
                    showResultsImmediately: true,
                    allowReview: true,
                },
            },
        },
        recommendedNextActions: ['review_event_status', 'publish_exam_for_learners'],
    },
    {
        key: 'design_course',
        label: 'Design Course',
        description: 'Create chapters and lessons at a higher level, and return upload/transcript task planning.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use after create_course when you want to structure the course without manually calling chapter and lesson CRUD tools.',
        inputSummary: 'Required: course, mode. Use manual_outline to explicitly provide chapters/lessons, or generate_outline to create a scaffolded outline from a brief.',
        notes: [
            'This tool creates chapters and lessons immediately.',
            'Asset uploads and transcript processing are not executed here; this tool returns planning tasks for those follow-up steps.',
        ],
        parameters: [
            {
                name: 'course',
                label: 'Course',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | slug | title',
                description: 'Course to structure.',
                howToFill: 'Use a course id, slug, or exact title from your current workspace.',
                referenceRule: {
                    entity: 'course',
                    acceptedForms: ['id', 'slug', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'slug', 'title'],
                },
                example: 'RTC Audio Basics Course',
            },
            {
                name: 'mode',
                label: 'Mode',
                inputKind: 'enum',
                required: 'mandatory',
                type: 'enum',
                description: 'How the structure should be designed.',
                howToFill: 'Use manual_outline when you already know the chapters/lessons. Use generate_outline when you want a scaffold created from a brief.',
                acceptedValues: [
                    enumOption('generate_outline', 'Generate Outline', 'Create a scaffolded outline from a brief'),
                    enumOption('manual_outline', 'Manual Outline', 'Create chapters and lessons from explicit input'),
                ],
                example: 'manual_outline',
            },
            {
                name: 'brief',
                label: 'Brief',
                inputKind: 'free_text',
                required: 'conditional',
                type: 'string',
                description: 'Design brief for scaffold generation.',
                howToFill: 'Required for generate_outline. Describe the audience, scope, and learning intent.',
                example: 'Design a 3-lesson intro course for new RTC CSEs.',
                defaultBehavior: 'Ignored when mode is manual_outline.',
            },
            {
                name: 'targetAudience',
                label: 'Target Audience',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Who the course is for.',
                howToFill: 'Use a short audience description.',
                example: 'New RTC CSE team members',
            },
            {
                name: 'lessonCount',
                label: 'Lesson Count',
                inputKind: 'number',
                required: 'optional',
                type: 'integer',
                description: 'Preferred lesson count when generating a scaffold.',
                howToFill: 'Use a small integer such as 3 or 5.',
                example: 3,
                defaultBehavior: 'Defaults to 3 when omitted in generate_outline mode.',
            },
            {
                name: 'chapters',
                label: 'Chapters',
                inputKind: 'object_array',
                required: 'conditional',
                type: 'array<object>',
                description: 'Explicit chapter and lesson structure.',
                howToFill: 'Required for manual_outline. Provide chapter titles and lesson entries.',
                example: [
                    {
                        title: 'Foundation',
                        lessons: [
                            {
                                title: 'RTC Audio Flow',
                                objective: 'Explain the audio path',
                                summary: 'Introduce the basic RTC audio path.',
                            },
                        ],
                    },
                ],
                defaultBehavior: 'Ignored when mode is generate_outline.',
            },
            {
                name: 'assetPlan',
                label: 'Asset Plan',
                inputKind: 'object_array',
                required: 'optional',
                type: 'array<object>',
                description: 'Optional upload planning for lesson assets.',
                howToFill: 'Use lessonRef plus asset type and source kind. The tool returns ready/unresolved upload tasks.',
                example: [
                    {
                        lessonRef: 'RTC Audio Flow',
                        assetType: 'VIDEO',
                        title: 'Audio Demo Video',
                        sourceKind: 'upload',
                        transcriptNeeded: true,
                    },
                ],
            },
            {
                name: 'transcriptPlan',
                label: 'Transcript Plan',
                inputKind: 'object_array',
                required: 'optional',
                type: 'array<object>',
                description: 'Optional transcript planning for created lessons.',
                howToFill: 'Use lessonRef and language settings. The tool returns ready/unresolved transcript tasks.',
                example: [
                    {
                        lessonRef: 'RTC Audio Flow',
                        languageCode: 'en',
                        setAsDefaultSubtitle: true,
                        setAsPrimaryForAI: true,
                    },
                ],
            },
        ],
        minimalExample: {
            title: 'Generate Scaffold',
            input: {
                course: 'RTC Audio Basics Course',
                mode: 'generate_outline',
                brief: 'Design a 3-lesson intro course for new RTC CSEs.',
            },
        },
        fullExample: {
            title: 'Manual Outline',
            input: {
                course: 'RTC Audio Basics Course',
                mode: 'manual_outline',
                chapters: [
                    {
                        title: 'Foundation',
                        lessons: [
                            {
                                title: 'RTC Audio Flow',
                                objective: 'Explain the audio path',
                                summary: 'Introduce the basic RTC audio path.',
                            },
                            {
                                title: 'Common No-Audio Issues',
                                objective: 'Recognize common failure modes',
                                summary: 'Show the most frequent no-audio scenarios.',
                            },
                        ],
                    },
                ],
                assetPlan: [
                    {
                        lessonRef: 'RTC Audio Flow',
                        assetType: 'VIDEO',
                        title: 'Audio Demo Video',
                        sourceKind: 'upload',
                        transcriptNeeded: true,
                    },
                ],
                transcriptPlan: [
                    {
                        lessonRef: 'RTC Audio Flow',
                        languageCode: 'en',
                        setAsDefaultSubtitle: true,
                        setAsPrimaryForAI: true,
                    },
                ],
            },
        },
        recommendedNextActions: ['review_event_status'],
    },
    {
        key: 'design_exam_questions',
        label: 'Design Exam Questions',
        description: 'Create questions manually or generate them from a linked course/event source.',
        category: 'authoring',
        categoryLabel: 'Authoring',
        productionVisible: true,
        whenToUse: 'Use after create_exam when you want to add or generate questions without directly using question CRUD.',
        inputSummary: 'Required: exam, mode. Use manual_payload to write questions directly, generate_from_course to reuse a source course, or generate_from_event to derive the source course from an event.',
        notes: [
            'Generated questions use the existing AI exam-generation pipeline.',
            'If generated question points do not match the exam totalScore, this tool returns a warning instead of silently rewriting the exam scoring.',
        ],
        parameters: [
            {
                name: 'exam',
                label: 'Exam',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | title',
                description: 'Exam to populate with questions.',
                howToFill: 'Use an exam id or exact title from your workspace.',
                referenceRule: {
                    entity: 'exam',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'title'],
                },
                example: 'RTC Audio Basics Assessment',
            },
            {
                name: 'mode',
                label: 'Mode',
                inputKind: 'enum',
                required: 'mandatory',
                type: 'enum',
                description: 'How questions should be created.',
                howToFill: 'Use manual_payload to provide questions directly, or one of the generate modes to use the AI generator.',
                acceptedValues: [
                    enumOption('generate_from_course', 'Generate From Course'),
                    enumOption('generate_from_event', 'Generate From Event'),
                    enumOption('manual_payload', 'Manual Payload'),
                ],
                example: 'generate_from_course',
            },
            {
                name: 'sourceCourse',
                label: 'Source Course',
                inputKind: 'reference',
                required: 'conditional',
                type: 'id | slug | title',
                description: 'Course used as the question-generation source.',
                howToFill: 'Required when mode is generate_from_course.',
                referenceRule: {
                    entity: 'course',
                    acceptedForms: ['id', 'slug', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'RTC Audio Basics Course',
                defaultBehavior: 'Ignored for other modes.',
            },
            {
                name: 'sourceEvent',
                label: 'Source Event',
                inputKind: 'reference',
                required: 'conditional',
                type: 'id | title',
                description: 'Event used to resolve the source course for question generation.',
                howToFill: 'Required when mode is generate_from_event.',
                referenceRule: {
                    entity: 'event',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                },
                example: 'RTC Audio Basics',
                defaultBehavior: 'Ignored for other modes.',
            },
            {
                name: 'questionCount',
                label: 'Question Count',
                inputKind: 'number',
                required: 'optional',
                type: 'integer',
                description: 'How many questions to generate.',
                howToFill: 'Use a positive integer. If omitted, the tool derives a count from the exam total score.',
                example: 10,
            },
            {
                name: 'difficultyMix',
                label: 'Difficulty Mix',
                inputKind: 'enum',
                required: 'optional',
                type: 'enum',
                description: 'Difficulty setting for generated questions.',
                howToFill: 'Choose a fixed difficulty or mixed.',
                acceptedValues: [
                    enumOption('EASY', 'Easy'),
                    enumOption('MEDIUM', 'Medium'),
                    enumOption('HARD', 'Hard'),
                    enumOption('mixed', 'Mixed'),
                ],
                example: 'mixed',
                defaultBehavior: 'Defaults to mixed.',
            },
            {
                name: 'questionTypes',
                label: 'Question Types',
                inputKind: 'string_array',
                required: 'optional',
                type: 'ExamQuestionType[]',
                description: 'Question types to create or generate.',
                howToFill: 'Use one or more supported question types.',
                example: ['MULTIPLE_CHOICE', 'TRUE_FALSE'],
                defaultBehavior: 'Defaults to MULTIPLE_CHOICE for generation modes.',
            },
            {
                name: 'coverageNotes',
                label: 'Coverage Notes',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'Topic or focus hints for generated questions.',
                howToFill: 'Use a short comma-separated or sentence-style topic list.',
                example: 'Cover audio flow, no-audio issues, and troubleshooting steps.',
            },
            {
                name: 'questions',
                label: 'Questions',
                inputKind: 'object_array',
                required: 'conditional',
                type: 'array<object>',
                description: 'Manual question payload.',
                howToFill: 'Required for manual_payload. Provide question objects compatible with the exam question model.',
                example: [
                    {
                        type: 'MULTIPLE_CHOICE',
                        question: 'Which step should you check first when there is no audio?',
                        options: ['ICE state', 'Audio device routing', 'Video bitrate', 'Resolution'],
                        correctAnswer: 'Audio device routing',
                        points: 10,
                    },
                ],
                defaultBehavior: 'Ignored for generation modes.',
            },
        ],
        minimalExample: {
            title: 'Generate From Course',
            input: {
                exam: 'RTC Audio Basics Assessment',
                mode: 'generate_from_course',
                sourceCourse: 'RTC Audio Basics Course',
                questionCount: 10,
            },
        },
        fullExample: {
            title: 'Manual Question Payload',
            input: {
                exam: 'RTC Audio Basics Assessment',
                mode: 'manual_payload',
                questions: [
                    {
                        type: 'MULTIPLE_CHOICE',
                        difficulty: 'MEDIUM',
                        question: 'Which step should you check first when there is no audio?',
                        options: ['ICE state', 'Audio device routing', 'Video bitrate', 'Resolution'],
                        correctAnswer: 'Audio device routing',
                        points: 10,
                        explanation: 'Basic endpoint routing checks should come before deeper network analysis.',
                    },
                ],
            },
        },
        recommendedNextActions: ['review_event_status', 'publish_exam_for_learners'],
    },
    {
        key: 'review_event_status',
        label: 'Review Event Status',
        description: 'Business-facing alias for checking event readiness and linked course/exam execution state.',
        category: 'operations',
        categoryLabel: 'Operations',
        productionVisible: true,
        whenToUse: 'Use after authoring work to inspect linked content, transcript readiness, and next actions for an event.',
        inputSummary: 'Required: event. You can use an event id or exact title.',
        parameters: [
            {
                name: 'event',
                label: 'Event',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | title',
                description: 'Event to review.',
                howToFill: 'Use an event id or exact title from your workspace.',
                referenceRule: {
                    entity: 'event',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'title'],
                },
                example: 'RTC Audio Basics',
            },
        ],
        minimalExample: {
            title: 'Review One Event',
            input: {
                event: 'RTC Audio Basics',
            },
        },
        recommendedNextActions: ['create_course', 'create_exam', 'design_course', 'design_exam_questions'],
    },
    {
        key: 'share_course_with_learners',
        label: 'Share Course With Learners',
        description: 'Assign active learners to a published course using a business-friendly course reference.',
        category: 'operations',
        categoryLabel: 'Operations',
        productionVisible: true,
        whenToUse: 'Use after a course is published and ready to be shared with learners.',
        inputSummary: 'Required: course, userIds. The course reference can be an id, slug, or exact title.',
        notes: ['Each userId must belong to an active learner account.'],
        parameters: [
            {
                name: 'course',
                label: 'Course',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | slug | title',
                description: 'Published course reference.',
                howToFill: 'Use a course id, slug, or exact title that is already in PUBLISHED status.',
                referenceRule: {
                    entity: 'course',
                    acceptedForms: ['id', 'slug', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'slug', 'title'],
                },
                example: 'RTC Audio Basics Course',
            },
            {
                name: 'userIds',
                label: 'Learner User IDs',
                inputKind: 'string_array',
                required: 'mandatory',
                type: 'uuid[]',
                description: 'Learner user UUID array.',
                howToFill: 'Use one or more active learner UUIDs.',
                example: ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'],
                validation: { minItems: 1, unique: true },
                commonMistakes: ['Passing SME or ADMIN user IDs instead of active learner IDs.'],
            },
            {
                name: 'sendNotification',
                label: 'Send Notification',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether learners should be notified immediately.',
                howToFill: 'Use false for smoke tests. Use true only when you are ready to notify real learners.',
                example: false,
                defaultBehavior: 'Defaults to false.',
            },
        ],
        minimalExample: {
            title: 'Share With One Learner',
            input: {
                course: 'RTC Audio Basics Course',
                userIds: ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'],
            },
        },
        fullExample: {
            title: 'Share And Notify',
            input: {
                course: 'RTC Audio Basics Course',
                userIds: ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'],
                sendNotification: true,
            },
        },
        recommendedNextActions: ['review_event_status'],
    },
    {
        key: 'publish_exam_for_learners',
        label: 'Publish Exam For Learners',
        description: 'Publish an approved exam and optionally create learner invitations using a business-friendly exam reference.',
        category: 'operations',
        categoryLabel: 'Operations',
        productionVisible: true,
        whenToUse: 'Use after exam review is complete and the exam is ready for learner access.',
        inputSummary: 'Required: exam. userIds is optional. The exam reference can be an id or exact title.',
        notes: [
            'The exam must already be APPROVED.',
            'If there are no existing invitations, some flows still require userIds.',
        ],
        parameters: [
            {
                name: 'exam',
                label: 'Exam',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'id | title',
                description: 'Approved exam reference.',
                howToFill: 'Use an exam id or exact title that is already APPROVED.',
                referenceRule: {
                    entity: 'exam',
                    acceptedForms: ['id', 'title', 'name'],
                    recommendedSourceTool: 'list_my_workspace',
                    matchPriority: ['id', 'title'],
                },
                example: 'RTC Audio Basics Assessment',
            },
            {
                name: 'userIds',
                label: 'Learner User IDs',
                inputKind: 'string_array',
                required: 'optional',
                type: 'uuid[]',
                description: 'Learner UUIDs to invite during publish.',
                howToFill: 'Use learner UUIDs only when invitations should be created now.',
                example: ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'],
                defaultBehavior: 'If omitted, the publish step relies on existing invitation state.',
            },
            {
                name: 'sendNotification',
                label: 'Send Notification',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Whether invited learners should be notified immediately.',
                howToFill: 'Use false for tests and true only when you are ready for real notification delivery.',
                example: false,
                defaultBehavior: 'Defaults to false.',
            },
        ],
        minimalExample: {
            title: 'Publish One Exam',
            input: {
                exam: 'RTC Audio Basics Assessment',
            },
        },
        fullExample: {
            title: 'Publish And Invite',
            input: {
                exam: 'RTC Audio Basics Assessment',
                userIds: ['aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'],
                sendNotification: false,
            },
        },
        recommendedNextActions: ['review_event_status'],
    },
    {
        key: 'prepare_transcript_upload',
        label: 'Prepare Transcript Upload',
        description: 'Create transcript upload metadata for a lesson video track.',
        category: 'advanced',
        categoryLabel: 'Advanced',
        whenToUse: 'Use only after a lesson and at least one lesson video already exist.',
        inputSummary: 'Required: lessonId, filename. videoAssetId is optional when the lesson has exactly one video asset.',
        notes: [
            'Use a .vtt filename and text/vtt contentType.',
            'If the lesson has one video asset, the server auto-selects it. If the lesson has multiple video assets, send videoAssetId explicitly.',
            'This tool now returns requiredHeaders and recommendedNextInputs for transcript processing.',
        ],
        parameters: [
            {
                name: 'lessonId',
                label: 'Lesson',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'uuid',
                description: 'Lesson UUID that owns the transcript track.',
                howToFill: 'Use lessonId from review_event_status or another trusted workflow response.',
                referenceRule: {
                    entity: 'lesson',
                    acceptedForms: ['id'],
                    recommendedSourceTool: 'review_event_status',
                },
                example: '77777777-7777-7777-7777-777777777777',
            },
            {
                name: 'videoAssetId',
                label: 'Video Asset',
                inputKind: 'reference',
                required: 'conditional',
                type: 'uuid',
                description: 'Video asset UUID under the same lesson.',
                howToFill: 'Omit it only when the lesson has exactly one video asset. When multiple video assets exist, use the exact video asset UUID from review_event_status.',
                referenceRule: {
                    entity: 'asset',
                    acceptedForms: ['id'],
                    recommendedSourceTool: 'review_event_status',
                },
                example: '88888888-8888-8888-8888-888888888888',
                defaultBehavior: 'If omitted and the lesson has one video asset, the backend auto-resolves it.',
                commonMistakes: ['Passing a video asset that belongs to a different lesson.'],
            },
            {
                name: 'filename',
                label: 'Filename',
                inputKind: 'free_text',
                required: 'mandatory',
                type: 'string',
                description: 'Subtitle filename to upload.',
                howToFill: 'Use a `.vtt` filename that matches the transcript language.',
                example: 'lesson-transcript-en.vtt',
                validation: { minLength: 1, maxLength: 255 },
            },
            {
                name: 'contentType',
                label: 'Content Type',
                inputKind: 'enum',
                required: 'optional',
                type: 'enum',
                description: 'MIME type for the transcript upload.',
                howToFill: 'Keep it as text/vtt.',
                acceptedValues: [enumOption('text/vtt', 'text/vtt', 'WebVTT subtitle file')],
                example: 'text/vtt',
                defaultBehavior: 'If omitted, the backend uses its transcript upload default.',
            },
            {
                name: 'languageCode',
                label: 'Language Code',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string',
                description: 'Language code for the transcript track.',
                howToFill: 'Use short language codes such as en or zh-CN.',
                example: 'en',
            },
            {
                name: 'label',
                label: 'Subtitle Label',
                inputKind: 'free_text',
                required: 'optional',
                type: 'string | null',
                description: 'User-facing subtitle label.',
                howToFill: 'Use the visible track label shown to learners.',
                example: 'English',
            },
            {
                name: 'replaceExistingLanguage',
                label: 'Replace Existing Language',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Replace an existing transcript in the same language.',
                howToFill: 'Use true only when you intend to archive the current track for the same language.',
                example: false,
                defaultBehavior: 'If omitted, the backend uses its transcript replacement default.',
            },
            {
                name: 'setAsDefaultSubtitle',
                label: 'Set As Default Subtitle',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Make this track the default subtitle shown to learners.',
                howToFill: 'Use true when this should be the learner-facing default subtitle.',
                example: true,
            },
            {
                name: 'setAsPrimaryForAI',
                label: 'Set As Primary For AI',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Use this transcript as the primary source for AI processing.',
                howToFill: 'Use true when knowledge extraction should be based on this track.',
                example: true,
            },
        ],
        minimalExample: {
            title: 'Single-Video Lesson',
            input: {
                lessonId: '77777777-7777-7777-7777-777777777777',
                filename: 'lesson-transcript-en.vtt',
                contentType: 'text/vtt',
            },
        },
        fullExample: {
            title: 'Explicit Video Selection',
            input: {
                lessonId: '77777777-7777-7777-7777-777777777777',
                videoAssetId: '88888888-8888-8888-8888-888888888888',
                filename: 'lesson-transcript-en.vtt',
                contentType: 'text/vtt',
                languageCode: 'en',
                label: 'English',
                setAsDefaultSubtitle: true,
                setAsPrimaryForAI: true,
            },
        },
        recommendedNextActions: ['process_transcript_knowledge', 'review_event_status'],
    },
    {
        key: 'process_transcript_knowledge',
        label: 'Process Transcript Knowledge',
        description: 'Queue transcript parsing and knowledge-context generation for a lesson.',
        category: 'advanced',
        categoryLabel: 'Advanced',
        whenToUse: 'Use after a transcript has been uploaded to its presigned URL and should be parsed for AI.',
        inputSummary: 'Required: lessonId. Usually set processTranscript=true and processKnowledge=true.',
        notes: [
            'transcriptId is optional when the lesson already has a primary transcript.',
            'If both processTranscript and processKnowledge are omitted, the server defaults both to true.',
            'knowledgePromptTemplateId must reference an active template for the transcript-to-knowledge use case.',
        ],
        parameters: [
            {
                name: 'lessonId',
                label: 'Lesson',
                inputKind: 'reference',
                required: 'mandatory',
                type: 'uuid',
                description: 'Lesson UUID whose pipeline should run.',
                howToFill: 'Use the lessonId from prepare_transcript_upload or review_event_status.',
                referenceRule: {
                    entity: 'lesson',
                    acceptedForms: ['id'],
                    recommendedSourceTool: 'prepare_transcript_upload',
                },
                example: '77777777-7777-7777-7777-777777777777',
            },
            {
                name: 'transcriptId',
                label: 'Transcript Track',
                inputKind: 'reference',
                required: 'optional',
                type: 'uuid',
                description: 'Specific transcript track UUID to process.',
                howToFill: 'Use a transcriptId when the lesson has multiple transcript tracks and you want one specific track.',
                referenceRule: {
                    entity: 'asset',
                    acceptedForms: ['id'],
                    recommendedSourceTool: 'prepare_transcript_upload',
                },
                example: '99999999-9999-9999-9999-999999999999',
                defaultBehavior: 'If omitted, the backend uses the current primary transcript for AI.',
            },
            {
                name: 'processTranscript',
                label: 'Process Transcript',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Run transcript parsing and chunking.',
                howToFill: 'Keep true for the normal first run.',
                example: true,
            },
            {
                name: 'processKnowledge',
                label: 'Process Knowledge',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Run knowledge and anchor generation.',
                howToFill: 'Keep true if you want AI outputs generated from the transcript.',
                example: true,
            },
            {
                name: 'force',
                label: 'Force Re-run',
                inputKind: 'boolean',
                required: 'optional',
                type: 'boolean',
                description: 'Force a re-run even if outputs already exist.',
                howToFill: 'Use only when you explicitly want to cancel active jobs or refresh stale results.',
                example: false,
            },
            {
                name: 'knowledgePromptTemplateId',
                label: 'Knowledge Prompt Template',
                inputKind: 'reference',
                required: 'optional',
                type: 'uuid | null',
                description: 'Optional override prompt template for knowledge extraction.',
                howToFill: 'Use only when you know a specific active transcript-to-knowledge template should override the default.',
                referenceRule: {
                    entity: 'template',
                    acceptedForms: ['id'],
                },
                defaultBehavior: 'If omitted, the backend uses the default knowledge prompt configuration.',
            },
        ],
        minimalExample: {
            title: 'Normal First Run',
            input: {
                lessonId: '77777777-7777-7777-7777-777777777777',
                processTranscript: true,
                processKnowledge: true,
            },
        },
        fullExample: {
            title: 'Process One Known Track',
            input: {
                lessonId: '77777777-7777-7777-7777-777777777777',
                transcriptId: '99999999-9999-9999-9999-999999999999',
                processTranscript: true,
                processKnowledge: true,
                force: true,
            },
        },
        recommendedNextActions: ['review_event_status'],
    },
    {
        key: 'list_my_series_badges',
        label: 'List My Domain Badges',
        description: 'Show domain badge progressions for the product domains in SME scope.',
        category: 'insights',
        categoryLabel: 'Insights',
        whenToUse: 'Use when you want to inspect badge ladders, threshold stars, and current unlock history in your domains.',
        inputSummary: 'No parameters. Leave the JSON as an empty object.',
        parameters: [],
        minimalExample: {
            title: 'All Badge Ladders',
            input: {},
        },
        recommendedNextActions: ['list_my_workspace', 'create_badge', 'create_series'],
    },
]

export const smeMcpToolMetadataByName = Object.fromEntries(
    smeMcpToolMetadata.map((tool) => [tool.key, tool])
) as Record<(typeof smeMcpToolMetadata)[number]['key'], SmeMcpToolMetadata>

export const getSmeMcpToolMetadata = (toolName: keyof typeof smeMcpToolMetadataByName) =>
    smeMcpToolMetadataByName[toolName]

export const getSmeMcpToolParameterMetadata = (
    toolName: keyof typeof smeMcpToolMetadataByName,
    parameterName: string
) => smeMcpToolMetadataByName[toolName].parameters.find((parameter) => parameter.name === parameterName)
