INSERT INTO "ai_prompt_templates" (
    "id",
    "name",
    "description",
    "useCase",
    "template",
    "systemPrompt",
    "userPrompt",
    "variables",
    "provider",
    "model",
    "temperature",
    "maxTokens",
    "responseFormat",
    "isActive",
    "createdAt",
    "updatedAt"
)
VALUES
(
    '81da60b2-3d7b-40f1-8a90-42c0f3c791a1',
    'learning_agent_lesson_coach_default',
    'Default prompt and model configuration for the Lesson Coach.',
    'LEARNING_AGENT_LESSON_COACH',
    $lesson_coach_system$You are a learning coach for a CSE training platform.
Use only the supplied course knowledge context, progress data, and recent exam weakness data.
Return concise Markdown. Include timestamp citations like [00:01:23] when referring to lesson content.
Do not invent product facts or training requirements that are not in the supplied context.
If recent exam weakness data is relevant, connect the lesson focus to those gaps. If it is not relevant, say so briefly and prioritize the lesson context.$lesson_coach_system$,
    $lesson_coach_system$You are a learning coach for a CSE training platform.
Use only the supplied course knowledge context, progress data, and recent exam weakness data.
Return concise Markdown. Include timestamp citations like [00:01:23] when referring to lesson content.
Do not invent product facts or training requirements that are not in the supplied context.
If recent exam weakness data is relevant, connect the lesson focus to those gaps. If it is not relevant, say so briefly and prioritize the lesson context.$lesson_coach_system$,
    $lesson_coach_user$Course: {{courseTitle}}
Chapter: {{chapterTitle}}
Lesson: {{lessonTitle}}
Course progress: {{courseProgressPercent}}% ({{enrollmentStatus}})
Lesson completed: {{lessonCompleted}}
Watched duration seconds: {{watchedDurationSeconds}}
Last timestamp seconds: {{lastTimestampSeconds}}
Current timestamp seconds: {{currentTimestampSeconds}}

Key moments:
{{keyMomentsJson}}

Recent exam weakness data for this course:
{{examWeaknessJson}}

Knowledge context XML:
{{knowledgeContextXml}}

Create a practical coaching response with these sections:
1. What to focus on now
2. Why this matters for your recent exam gaps
3. 3 checkpoint questions
4. Next 10-minute study path$lesson_coach_user$,
    ARRAY[
        'courseTitle',
        'chapterTitle',
        'lessonTitle',
        'courseProgressPercent',
        'enrollmentStatus',
        'lessonCompleted',
        'watchedDurationSeconds',
        'lastTimestampSeconds',
        'currentTimestampSeconds',
        'keyMomentsJson',
        'examWeaknessJson',
        'knowledgeContextXml'
    ]::TEXT[],
    'vexke',
    'gpt-5.4',
    0.2,
    1600,
    'TEXT',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '1cc334b0-0b23-4ded-9049-b786eb6e0c30',
    'learning_agent_exam_mistake_review_default',
    'Default model configuration for the Exam Mistake Review Coach. Runtime prompt is generated by the application.',
    'LEARNING_AGENT_EXAM_MISTAKE_REVIEW',
    'Learning Agent Exam Mistake Review runtime prompt is generated by the application.',
    'Learning Agent Exam Mistake Review runtime prompt is generated by the application.',
    NULL,
    ARRAY[]::TEXT[],
    'vexke',
    'gpt-5.4',
    0.2,
    1600,
    'TEXT',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    '99eb26aa-e926-4f27-a53a-a016f1d0943f',
    'learning_agent_plan_default',
    'Default model configuration for the Learning Plan Agent. Runtime prompt is generated by the application.',
    'LEARNING_AGENT_PLAN',
    'Learning Agent Learning Plan runtime prompt is generated by the application.',
    'Learning Agent Learning Plan runtime prompt is generated by the application.',
    NULL,
    ARRAY[]::TEXT[],
    'vexke',
    'gpt-5.4',
    0.2,
    1600,
    'TEXT',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("name") DO UPDATE SET
    "description" = EXCLUDED."description",
    "template" = EXCLUDED."template",
    "systemPrompt" = EXCLUDED."systemPrompt",
    "userPrompt" = EXCLUDED."userPrompt",
    "variables" = EXCLUDED."variables",
    "provider" = EXCLUDED."provider",
    "model" = EXCLUDED."model",
    "temperature" = EXCLUDED."temperature",
    "maxTokens" = EXCLUDED."maxTokens",
    "responseFormat" = EXCLUDED."responseFormat",
    "isActive" = EXCLUDED."isActive",
    "updatedAt" = CURRENT_TIMESTAMP;

INSERT INTO "ai_prompt_defaults" (
    "id",
    "useCase",
    "templateId",
    "createdAt",
    "updatedAt"
)
VALUES
(
    'ebd5b683-e47a-43f2-932a-140df8ded6a1',
    'LEARNING_AGENT_LESSON_COACH',
    '81da60b2-3d7b-40f1-8a90-42c0f3c791a1',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'cd118f82-37fe-446d-8613-780c31e7de97',
    'LEARNING_AGENT_EXAM_MISTAKE_REVIEW',
    '1cc334b0-0b23-4ded-9049-b786eb6e0c30',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'ad1d6fbf-e60c-4a0a-9e5b-96445aeea4a4',
    'LEARNING_AGENT_PLAN',
    '99eb26aa-e926-4f27-a53a-a016f1d0943f',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("useCase") DO NOTHING;
