ALTER TYPE "AIPromptUseCase" ADD VALUE IF NOT EXISTS 'LEARNING_AGENT_LESSON_COACH';
ALTER TYPE "AIPromptUseCase" ADD VALUE IF NOT EXISTS 'LEARNING_AGENT_EXAM_MISTAKE_REVIEW';
ALTER TYPE "AIPromptUseCase" ADD VALUE IF NOT EXISTS 'LEARNING_AGENT_PLAN';
